# Generated by Django 3.1.7 on 2021-04-08 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisorAccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('canTakeSurvey', 'can take survey'), ('canViewOwnResults', 'can see own results'), ('canSeeAdviseeSurvey', 'can see advisee survey')),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Advisee', to='user.advisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentAccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('canTakeSurvey', 'can take survey'), ('canViewOwnResults', 'can see own results')),
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ManyToManyField(to='base.Survey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminAccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('canCreateSurvey', 'can create survey'), ('canEditSurvey', 'can edit survey'), ('canDeleteSurvey', 'can delete survey'), ('canCreateCategory', 'can create category'), ('canEditCategory', 'can edit category'), ('canDeleteCategory', 'can delete category'), ('canCreateQuestion', 'can create question'), ('canEditQuestion', 'can edit question'), ('canDeleteQuestion', 'can delete question'), ('canTakeSurvey', 'can take survey'), ('canViewOwnResults', 'can see own results'), ('canCreateUser', 'can create user'), ('canUpdateUser', 'can update user'), ('canDeleteUser', 'can delete user')),
            },
        ),
    ]
