# Generated by Django 3.1.6 on 2021-03-19 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOfCategory', models.CharField(help_text='Please enter a title for this category, ex) Computer Skills.', max_length=100)),
                ('lowWeightText', models.CharField(default='Not like me at all', help_text='Please enter flavor text for the low weight of the category, ex) Not like me at all', max_length=50)),
                ('highWeightText', models.CharField(default='Extremely like me', help_text='Please enter flavor text for the high weight of the category, ex) Extremely like me', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOfSurvey', models.CharField(help_text='Please enter a name for the survey', max_length=50)),
                ('directions', models.CharField(help_text='Please enter any directions to take the survey', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this survey', primary_key=True, serialize=False)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(help_text='Please enter a prompt. ex) I know how to install software on my computer.', max_length=100)),
                ('score', models.IntegerField(blank=True, choices=[(0, 'weight 0'), (1, 'weight 1'), (2, 'weight 2'), (3, 'weight 3'), (4, 'weight 4')], help_text='Results of question', null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.category', verbose_name='Parent Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='base.survey', verbose_name='Parent Survey'),
        ),
    ]
