# Generated by Django 3.1.7 on 2021-04-08 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOfCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Input_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Option_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_is_required', models.BooleanField()),
                ('is_multi_option_answer', models.BooleanField()),
                ('input_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.input_type')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.option_group')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOfSurvey', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('surveySlug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('survey_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.survey')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('question_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.question')),
                ('survey_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Option_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=20)),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.option_group')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='survey_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=20)),
                ('survey_question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.survey_question')),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
