# Generated by Django 3.1.7 on 2021-03-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categorySlug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questionSlug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='surveySlug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
