# Generated by Django 3.1.7 on 2021-04-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='surveySlug',
            field=models.SlugField(default='cool', unique=True),
            preserve_default=False,
        ),
    ]
