# Generated by Django 3.1.7 on 2021-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_survey_surveyslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categorySlug',
            field=models.SlugField(default='very_cool', unique=True),
            preserve_default=False,
        ),
    ]
