# Generated by Django 3.1.7 on 2021-03-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210325_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorySlug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionSlug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveySlug',
            field=models.SlugField(unique=True),
        ),
    ]
